config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'

  get "/fields/all", to: "fields#show_all", as: "fields_all"
  resources :businesses, only: [:new, :create, :index, :show]
  resources :fields, only: [:new, :show, :create, :index]
  get "/schedule", to: "fields#schedule", as: "schedule"

  resources :bookings, only: [:index, :create, :edit, :update]
  resources :users, only: [:edit, :update]
end

app/views/shared/_booking_bill.html.erb
<div class="booking-box-info">
  <div class="booking-box-bill-top booking-box-info-top booking-box-bil-top ">
    <div class="booking-box-bill-top-center">
      <div class="booking-box-info-title">
        <h2>Pago</h2>
      </div>
      <div class="booking-box-info-subtitle booking-box-info-text-center
                  booking-box-info-main-subtitle booking-bill-subtitle">
        <% if @booking.splitable %>
          <p>Tarifa dividida entre todos los jugadores</p>
        <% end %>
      </div>
    </div>
  </div>
  <hr color="gray" size=0.75>
  <div class="booking-box-bill-mid booking-box-info-mid">
    <div class="billing-box-text booking-box-bill-total">
      <div class="booking-box-bill-text">
        <p>Precio x hora</p>
      </div>
      <div class="booking-box-bill-text">
        <p>
          <% total_price = total_price(@booking.field.price_cents) %>
          $ <%= humanize_price(total_price) %>
        </p>
      </div>
    </div>
    <% price_per_person = price_per_person(@booking.field.price_cents,
                          @booking.number_players)  %>
    <% if @booking.splitable %>
      <div class="billing-box-text booking-box-bill-per_player">
        <div class="booking-box-bill-text">
          <p>Precio por jugador</p>
        </div>
        <div class="booking-box-bill-text">
          $ <%= humanized_money(price_per_person) %>
        </div>
      </div>
    <% end %>

    <div class="billing-box-text booking-box-bill-paid">
      <div class="booking-box-bill-text" name="Pagan-todos-o-individual">
        <p>
          <%paid_players =
                  paid_players(@booking.splitable,
                  @booking.number_players,
                  count_paid_players(
                  @booking.booking_players))%>
         <%= paid_players %>
        </p>
      </div>
      <div class="booking-box-bill-text">
        <p>
          <% total_paid = total_paid(
                  count_paid_players(@booking.booking_players),
                  price_per_person) %>
          $ <%= humanize_price(total_paid) %>
        </p>
      </div>
    </div>
  </div>
  <hr color="gray" size=0.75>
  <div class="booking-box-bill-bottom booking-box-info-bottom">
    <div class="billing-box-text booking-box-bill-paid">
      <div class="billing-total">
        <div class="vl"></div>
        <h6>Pendiente por pagar</h6>
      </div>
      <div class="booking-box-bill-text booking-box-bill-total-text">
        <p>
          $ <%= humanize_price(total_price - total_paid) %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_booking_card.html.erb
<div class="card">
  <div
    class="card-top"
    style="background-image:
      linear-gradient(rgba(255,255,255, 0),
      rgba(0, 0, 0, 0.4)),
      url(<%= field_picture_or_generic(booking.field)%>);"
  >
     <%= business_logo_or_generic(booking.field.business, "card-top-business-logo booking-logo-center")%>
      <% if booking.date > Time.zone.now %>
        <% if booking.status == 'Pendiente' %>
          <div class='booking-card-status pending-booking'>
        <% elsif booking.status.nil? %>
          <div class='booking-card-status pending-booking'>
        <% elsif booking.status == 'Jugado' %>
          <div class='booking-card-status passed-booking'>
        <% elsif booking.status == 'Confirmada' %>
          <div class='booking-card-status approved-booking'>
        <% elsif booking.status == 'Cancelada' %>
          <div class='booking-card-status cancelled-booking'>
        <% end %>
      <% else %>
        <div class='booking-card-status passed-booking'>
      <% end %>
      <%= booking_status_text(booking) %>
      </div>
  </div>
  <div class="card-bottom">
    <div class="card-header booking-card-header">
      <h3 class="card-business-name booking-business-name-center"><%= booking.field.business.name%></h3>
      <div class="card-addreess booking-card-address-flex">
        <% if current_user.admin %>
          <%= "Reserva No. #{booking.id}" %>
        <% else %>
          <p><%= booking.field.business.address %></p>
        <% end %>
      </div>
      <div class="booking-schedule">
        <div class="booking-card-date">
          <h5><%= l(booking.date.to_date, format: '%A %d de %B') %></h5>
        </div>
        <div class="booking-card-hour">
          <h5><%= "#{format_hour(booking.date.hour)} - #{format_hour(booking.date.hour + 1)}" %></h5>
        </div>
      </div>
      <hr>
    </div>
    <div class="card-field-info booking-card-field-info">
      <div class="card-field-descripton text-center">
        <p class="card-field-name">
          <i class="fas fa-futbol"></i>
          <%= booking.field.name %>
        </p>
        <div class="booking-card-info-text text-center">
          Referencia de la cancha
        </div>
        <div class="card-field-capacity text-center booking-card-info-second-level">
          <i class="fas fa-users"></i>
          <p><%= booking.field.capacity %> (<%= booking.field.capacity / 2 %> vs. <%= booking.field.capacity / 2 %>)</p>
        </div>
        <div class="booking-card-info-text text-center">
          Capacidad de la cancha
        </div>
      </div>
      <div class="card-field-descripton text-center">
        <p class="card-price">
          <i class="fas fa-dollar-sign"></i>
          <%= humanized_money(booking.field.price) %>
        </p>
        <div class="booking-card-info-text text-center">
          Precio por hora
        </div>
        <div class="card-field-capacity text-center booking-card-info-second-level">
          <i class="fas fa-qrcode"></i>
          <p><%= booking.id %></p>
        </div>
        <div class="booking-card-info-text text-center">
          Código de reserva
        </div>
      </div>
    </div>
  <hr>
  </div>
  <div class="booking-card-link text-center">
    <% if current_user.admin %>
    <%= link_to "ACTUALIZAR ESTADO", edit_booking_path(booking)  %>
    <% else %>
    <a target="_blank" href=<%=  "https://www.google.com/maps/search/?api=1&query=#{booking.field.business.latitude},#{booking.field.business.longitude}" %> >
      <i class="fas fa-map-marker-alt"></i>
      VER UBICACIÓN
    </a>
    <% end %>
  </div>
</div>

app/views/shared/_booking_field.html.erb
<div class="field-players">
  <div class="field-players-container">
    <div class="row">
      <% confirmed_players(@booking.booking_players).each do |player| %>
        <div class="col-sm-2">
          <%= booking_avatar(player.user) %>
          <p> <%= player.user.email %> </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_booking_information.html.erb
<div class="booking-box-info">
  <div class="booking-box-info-top">
    <div class="booking-box-info-top-center">
      <div class="booking-box-info-title
              booking-box-info-business-name
              booking-box-info-text-center">
        <h2> <%= @booking.field.business.name  %> </h2>
      </div>
      <div class="booking-box-info-subtitle
              booking-box-info-text-center
              booking-box-info-main-subtitle">
        <p> <%= @booking.field.name %> </p>
      </div>
    </div>
  </div>
  <hr color="gray" size=0.75 margin = "5px 0 5px 0">
  <div class="booking-box-info-mid">
    <div class="booking-box-info-title booking-box-info-text-center">
      <i class="far fa-clock margin-rigt-icon"></i>
      <h4>Horario</h4>
    </div>
    <div class="booking-box-info-subtitle
            booking-box-info-date
            booking-box-info-text-center">
      <p> <%= l(@booking.date.to_date, format: '%A %d de %B') %> </p>
    </div>
    <div class="booking-box-info-space-around">
      <div class="booking-box-info-hours hours-beginig">
        <h6>Hora de inicio</h6>
        <p> <%= format_hour(@booking.date.hour) %> </p>
      </div>
      <div class="booking-box-info-hours hours-end">
        <h6>Hora de fin</h6>
        <p> <%= format_hour(@booking.date.hour+1) %> </p>
      </div>
    </div>
  </div>
  <hr color="gray" size=0.75>
  <div class="booking-box-info-bottom">
    <div class="booking-box-info-title booking-box-info-text-center">
      <i class="fas fa-map-marker-alt margin-rigt-icon"></i>
      <h4>Dirección</h4>
    </div>
    <div class="booking-box-info-subtitle
            booking-box-info-address
            booking-box-info-text-center">
      <p> <%= @booking.field.business.address %> </p>
    </div>
    <div class="booking-box-info-links booking-box-info-space-around">
      <div class="booking-box-info-links">
        <%= link_to "Como llegar", "#", class:"btn btn-additional-info"  %>
      </div>
      <div class="booking-box-info-links">
        <%= link_to "Ver sede", "#", class:"btn btn-additional-info"  %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_business_logo.html.erb
<div class="booking-business-logo">
  <%= business_banner = business_logo_or_generic(@booking.field.business, "booking-box-business-picture")%>
  <div
    style="background-image:
      linear-gradient(rgba(0,0,0, 0.4),
      rgba(0, 0, 0, 0.4)),
      url(<% business_banner %>);"
    >
  </div>
</div>

app/views/shared/_edit_user_form.html.erb
<div class="edit-user-form-wrapper" style="background-image:
      linear-gradient(rgba(255,255,255, 0),
      rgba(0, 0, 0, 0.4)),
      url(<%= cl_image_path('Default Pics/user-info-background.jpg')%>);"
  >
  <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "sessions-logo"%>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

        <div class="edit-user-form">
          <h2>Tu solicitud de reserva está casi completada</h2>
          <p>Solo necesitamos algunos datos más:</p>

          <%= simple_form_for([@user]) do |f| %>
           <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :first_name, label:"Tu nombre", required: true, autofocus: true %>
              <%= f.input :last_name, label:"Tu apellido", required: true %>
              <%= f.input :telefono,
                hint: "Celular o fijo",
                label:"Un número de contacto",
                required: true
              %>
              <%= f.input :identificacion,
                hint: "No debe contener especiales (como espacios, *, -)",
                label:"Y tu cédula o Id",
                required: true
              %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Completar solicitud", class: "btn btn-primary"%>
            </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_field-card.html.erb
<div class="card">
  <div
    class="card-top"
    style="background-image:
      linear-gradient(rgba(255,255,255, 0),
      rgba(0, 0, 0, 0.4)),
      url(<%= field_picture_or_generic(field)%>);"
  >
     <%= business_logo_or_generic(field.business, "card-top-business-logo")%>
  </div>
  <div class="card-bottom">
    <div class="card-header">
      <h3 class="card-business-name"><%= field.business.name%></h3>
      <p class="card-addreess"><%= field.business.address %></p>
    </div>
    <div class="card-field-info">
      <div class="card-field-descripton">
        <p class="card-field-name">
          <i class="fas fa-futbol"></i>
          <%= field.name %>
        </p>
        <div class="card-field-capacity">
          <i class="fas fa-users"></i>
          <p><%= field.capacity %> jugadores (<%= field.capacity / 2 %> vs. <%= field.capacity / 2 %>)</p>
        </div>
      </div>
        <p class="card-price">
          <i class="fas fa-dollar-sign"></i>
          <%= humanized_money(field.price) %> / Hora
        </p>
    </div>
    <div class="schedule-dropdown">
     <p>VER HORARIOS</p>
      <i class="fas fa-chevron-circle-down"></i>
    </div>
    <div class="card-available-hours card-collapsed">
      <hr class="card-line-divider">
      <i class="far fa-clock"></i>
      Selecciona uno de los horarios disponibles:
      <div class="schedule-container">
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
          <% @schedule.first[1][field.id.to_s].keys.each do |hour| %>
            <label class="schedule-btn btn btn-xs">
              <input
                type="radio"
                name="options"
                autocomplete="off"
                data-time="<%=hour.to_i%>"
                value= "<%= Date.parse(@date_range.first.to_s)%>"
              >
              <%= "#{hour} - #{hour.to_i + 1} "%>
            </label>
          <% end %>
        </div>
      </div>
      <div class="card-bottom-footer">
        <%= button_tag "NO HAS SELECCIONADO NINGÚN HORARIO",
            class: "card-cta btn btn-cta",
            "data-id": field.id,
            "data-toggle": "modal",
            "data-target":  "#myModal",
            disabled: true
        %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <script>
    swal({
          title: "",
          text: "<%= notice %>",
          icon: "success"
        });
  </script>
<% end %>

<% if alert %>
  <script>
    swal({
          title: "",
          text: "<%= alert %>",
          icon: "error"
        });
  </script>
<% end %>

app/views/shared/_loader.html.erb
<div class="loader-div">
  <svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve">
  <path opacity="0.4" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946
    s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634
    c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"/>
  <path fill="#000" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0
    C22.32,8.481,24.301,9.057,26.013,10.047z">
    <animateTransform attributeType="xml"
      attributeName="transform"
      type="rotate"
      from="0 20 20"
      to="360 20 20"
      dur="0.5s"
      repeatCount="indefinite"/>
    </path>
  </svg>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= "navbar-transparent" if controller_name == "pages" %> <%= "navbar-none" if controller_name == "registrations" || controller_name == "sessions" %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand hidden-xs" do %>
    <%= image_tag "logo.png"%>
  <% end %>
    <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg hidden-sm">
    <div class="dropdown" style="cursor: pointer;">
      <i class="fa fa-bars fa-2x dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to root_path do%>
              <i class="fas fa-home"></i>
              Inicio
            <% end %>
          </li>
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to fields_path do%>
              <i class="fas fa-futbol"></i>
              Busca una cancha
            <% end %>
          </li>
          <li>
            <%= link_to bookings_path do %>
              <i class="far fa-address-book"></i>
              <%= current_user.admin ? "Editar Reservas": "Mis reservas" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% else %>
        <li>
          <%= link_to root_path do%>
            <i class="fas fa-home"></i>
            Inicio
          <% end %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to fields_path do%>
            Busca una cancha
          <% end %>
        </li>
        <li>
          <%= link_to t(".sign_in", default: "Iniciar Sesion"),
            new_user_session_path,
            class: "navbar-wagon-item navbar-wagon-link"
          %>
        </li>
        <li>
          <%= link_to t(".sign_in", default: "Crea una cuenta"),
            new_user_registration_path,
            class: "navbar-wagon-item navbar-wagon-link"
          %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class=" <%= "navbar-none" unless action_name == "home" %> ">
    <%= image_tag "logo.png", class: "logo-banner-mobile logo-banner-hidden"%>
  </div>
  <div class="iteminvisible <%= "navbar-none" unless action_name == "home" %>">
    <i class="fa fa-bars fa-2x dropdown-toggle"></i>
  </div>
  <%= render 'shared/search-form-city' if controller_name == "fields" || controller_name == "bookings"  %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to (current_user.admin ? "Editar Reservas": "Mis reservas"), bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Canchas", fields_path, class: "navbar-wagon-item navbar-wagon-link" if controller_name != 'fields' %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.blank? %>
          <i class="fas fa-user-circle dropdown-toggle"  id = "navbar-wagon-menu" data-toggle= "dropdown"></i>
          <% else %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Canchas", fields_path, class: "navbar-wagon-item navbar-wagon-link" if controller_name != 'fields' %>
      <%= link_to t(".sign_in", default: "Crea una cuenta"),  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Iniciar Sesion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_search-form-capacity.html.erb
<%= form_with url: fields_path, method: :get, local: true do |f| %>
  <%= f.hidden_field :query,
    value: params[:query]
  %>
  <%= f.hidden_field :dates,
    value: params[:dates]
  %>
  <select name="capacity_limit" id="capacity_limit" class="queryinput form-control" size=5>
    <option value="" <%= "selected" unless params[:capacity_limit].present? %>>Cualquiera</option>
    <% Field::CAPACITY_RANGE.each do |value| %>
      <option <%= "selected" if value.to_s == params[:capacity_limit] %> value="<%= value %>">
        <%= value / 2 %> Vs. <%= value / 2 %>
      </option>
    <% end %>
  </select>

  <%= f.hidden_field :start_time,
    value: params[:start_time]
  %>

  <%= f.hidden_field :end_time,
    value: params[:end_time]
  %>

  <div class="filter-btns">
    <button data-toggle="dropdown" class= "btn btn-close-filter">CANCELAR</button>
    <%= f.submit "FILTRAR", name: nil, class: "btn btn-filter" %>
  </div>
<% end %>

app/views/shared/_search-form-city.html.erb
<div class="navbar-search-form-container">
  <%= form_with url: fields_path, method: :get, class: "form-inline", local: true do |f| %>
  <div class="navbar-search-form">
      <i class="fas fa-search"></i>
      <%= f.text_field :query,
        value: params[:query],
        id: "query",
        class: "",
        placeholder: "¿Donde quieres jugar?"
      %>
      <%= f.hidden_field :dates,
        value: params[:dates]
      %>
      <%= f.hidden_field :capacity_limit,
        value: params[:capacity_limit]
      %>
      <%= f.hidden_field :start_time,
        value: params[:start_time]
      %>
      <%= f.hidden_field :end_time,
        value: params[:end_time]
      %>
  </div>
  <% end %>
</div>

app/views/shared/_search-form-hours.html.erb
<%= form_with url: fields_path, method: :get, local: true do |f| %>
  <%= f.hidden_field :query,
    value: params[:query]
  %>
  <%= f.hidden_field :dates,
    value: params[:dates]
  %>
  <%= f.hidden_field :capacity_limit,
    value: params[:capacity_limit]
  %>
  <div id="slider"></div>
    <%= f.hidden_field :start_time,
      value: params[:start_time],
      id: "starttime"
    %>
    <%= f.hidden_field :end_time,
      value: params[:end_time],
      id:"endtime"
    %>
    <div class="filter-btns">
      <button data-toggle="dropdown" class= "btn btn-close-filter">CANCELAR</button>
      <%= f.submit "FILTRAR", name: nil, class: "btn btn-filter" %>
    </div>
<% end %>

app/views/shared/_search-form.html.erb
<div class="row">
    <%= form_with url: fields_path, method: :get, class: "field-search-form", local: true do |f| %>
    <div class="col-xs-12 col-sm-10 search-form-input">
      <%= f.text_field :dates,
        value: params[:dates],
        id: "dates",
        class: "datepicker datesize",
        placeholder: "¿Cuándo quieres jugar?"
      %>
    </div>

    <div class="col-xs-12 col-sm-2 search-form-input">
      <%= f.submit "BUSCAR", name: nil, class: "btn btn-banner full-width-padded" %>
    </div>
  <% end %>
</div>